CREATE TABLE IF NOT EXISTS `glpi_plugin_sservices_sservices` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
    `computers_id` INT UNSIGNED DEFAULT NULL,
    `plugin_sservices_categories_id` INT UNSIGNED DEFAULT NULL,
    `info` VARCHAR(255) DEFAULT NULL,
    `users_id` INT UNSIGNED DEFAULT NULL,
    `groups_id` INT UNSIGNED DEFAULT NULL,
    `plugin_sservices_localusers_id` INT UNSIGNED DEFAULT NULL,
    `plugin_sservices_visibilities_id` INT UNSIGNED DEFAULT NULL,
    `is_monitored` TINYINT(1) NOT NULL DEFAULT 0,
    `plugin_sservices_installationmethods_id` INT UNSIGNED DEFAULT NULL,
    `comment` TEXT DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `computers_id` (`computers_id`),
    KEY `plugin_sservices_categories_id` (`plugin_sservices_categories_id`),
    KEY `users_id` (`users_id`),
    KEY `groups_id` (`groups_id`),
    KEY `plugin_sservices_localusers_id` (`plugin_sservices_localusers_id`),
    KEY `plugin_sservices_visibilities_id` (`plugin_sservices_visibilities_id`),
    KEY `is_monitored` (`is_monitored`),
    KEY `plugin_sservices_installationmethods_id` (`plugin_sservices_installationmethods_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
