<?php

namespace GlpiPlugin\SServices;

use CommonDBTM;
use CommonGLPI;
use Computer;
use Dropdown;
use Glpi\Toolbox\URL;
use Html;
use MassiveAction;
use Search;
use Session;

class SService extends CommonDBTM
{
    public function can($ID, $right, array &$input = null): bool
    {
        return parent::can($ID, $right, $input);
    }

    public static function canView(): bool
    {
        return true;
    }

    public static function canCreate(): bool
    {
        return true;
    }

    public static function canDelete(): bool
    {
        return true;
    }

    public static function canUpdate(): bool
    {
        return true;
    }

    public static function canPurge(): bool
    {
        return true;
    }

    public function canDeleteItem(): bool
    {
        return parent::canDeleteItem(); // TODO: Change the autogenerated stub
    }

    public static function getNameField()
    {
        return 'id';
    }

    public function showForm($ID, $options = [])
    {
        global $CFG_GLPI;
        $this->initForm($ID, $options);
        $this->showFormHeader($options);

        if (!isset($options['display'])) {
            //display per default
            $options['display'] = true;
        }

        $computersId = $this->fields['computers_id'];
        if (!empty($options['computers_id'])) {
            $computersId = $options['computers_id'];
        }

        $params = $options;
        //do not display called elements per default; they'll be displayed or returned here
        $params['display'] = false;
        $params['candel'] = true;
        $params['withtemplate'] = '';

        echo "<tr  class='tab_bg_1'>";
        echo '<td>' . __('Computer', SSERVICES_SSERVICES) . '</td>';
        echo '<td>';
        \Computer::dropdown(
            [
                'name' => 'computers_id',
                'value' => $computersId,
            ]
        );
        echo '</td>';
        echo '</tr>';

        echo "<tr  class='tab_bg_1'>";
        echo '<td>' . __('Category', SSERVICES_SSERVICES) . '</td>';
        echo '<td>';
        Category::dropdown(
            [
                'name' => 'plugin_sservices_categories_id',
                'value' => $this->fields['plugin_sservices_categories_id'],
            ]
        );
        echo '</td>';
        echo '</tr>';

        echo '<tr>';
        echo '<td>' . __('Info', SSERVICES_SSERVICES) . '</td>';
        echo '<td>';
        echo Html::input(
            'info',
            [
                'value' => $this->fields['info'],
            ]
        );
        echo '</td>';
        echo '</tr>';

        echo "<tr  class='tab_bg_1'>";
        echo '<td>' . __('Technician in charge', SSERVICES_SSERVICES) . '</td>';
        echo '<td>';
        \User::dropdown(
            [
                'name' => 'users_id',
                'value' => $this->fields['users_id'],
                'right' => 'interface',
            ]
        );
        echo '</td>';
        echo '</tr>';

        echo "<tr  class='tab_bg_1'>";
        echo '<td>' . __('Group in charge', SSERVICES_SSERVICES) . '</td>';
        echo '<td>';
        \Group::dropdown(
            [
                'name' => 'groups_id',
                'value' => $this->fields['groups_id'],
            ]
        );
        echo '</td>';
        echo '</tr>';

        echo "<tr  class='tab_bg_1'>";
        echo '<td>' . __('Local User', SSERVICES_SSERVICES) . '</td>';
        echo '<td>';
        LocalUser::dropdown(
            [
                'name' => 'plugin_sservices_localusers_id',
                'value' => $this->fields['plugin_sservices_localusers_id'],
            ]
        );
        echo '</td>';
        echo '</tr>';

        echo "<tr  class='tab_bg_1'>";
        echo '<td>' . __('Visibility', SSERVICES_SSERVICES) . '</td>';
        echo '<td>';
        Visibility::dropdown(
            [
                'name' => 'plugin_sservices_visibilities_id',
                'value' => $this->fields['plugin_sservices_visibilities_id'],
            ]
        );
        echo '</td>';
        echo '</tr>';

        echo "<tr  class=''>";
        echo '<td>' . __('Monitored', SSERVICES_SSERVICES) . '</td>';
        echo '<td>';
        Dropdown::showYesNo('is_monitored', $this->fields['is_monitored']);
        echo '</td>';
        echo '</tr>';

        echo "<tr  class='tab_bg_1'>";
        echo '<td>' . __('Installation Method', SSERVICES_SSERVICES) . '</td>';
        echo '<td>';
        InstallationMethod::dropdown(
            [
                'name' => 'plugin_sservices_installationmethods_id',
                'value' => $this->fields['plugin_sservices_installationmethods_id'],
            ]
        );
        echo '</td>';
        echo '</tr>';

        echo '<tr>';
        echo '<td>' . __('Comment', SSERVICES_SSERVICES) . '</td>';
        echo '<td>';
        echo Html::input(
            'comment',
            [
                'value' => $this->fields['comment'],
            ]
        );
        echo '</td>';
        echo '</tr>';

//var_dump($this->can($ID, UPDATE), $params);

        $this->showFormButtons($params);
    }

    static function getMenuName()
    {
        return __('Services');
    }

    public static function getMenuContent()
    {
        $menuContent = parent::getMenuContent();
        $menuContent['page'] .= '?reset=reset';
        return $menuContent;
    }

    static function getIcon()
    {
        return "fas fa-heart";
    }

    public function rawSearchOptions()
    {
//        $tab = parent::rawSearchOptions();

        $tab = [];

        $tab[] = [
            'id' => 'common',
            'name' => __('Characteristics', SSERVICES_SSERVICES)
        ];

//       $tab[] = [
//           'id' => 100,
//           'table' => $this->getTable(),
//           'field' => 'id',
//           'name' => __('ID', SSERVICES_SSERVICES),
//           'datatype' => 'itemlink',
//           'massiveaction' => false,
//           'searchtype' => 'contains',
//        ];

// datatype for Computer changed from dropdown to itemlink
        $tab[] = [
            'id' => 300,
            'table' => 'glpi_computers',
            'field' => 'name',
            'name' => __('Computer', SSERVICES_SSERVICES),
            'linkfield' => 'computers_id',
             // datatype for Computer changed from dropdown to itemlink, now links to Computer Service list
            'datatype' => 'itemlink',
            'massiveaction' => true,
            //'searchtype' => 'contains', /* Not needed? Investigate further */
        ];

        $tab[] = [
            'id' => 400,
            'table' => $this->getTable(),
            'field' => 'info',
            'name' => __('Info', SSERVICES_SSERVICES),
            'datatype' => 'string',
            'massiveaction' => true,
        ];

        $tab[] = [
            'id' => 500,
            'table' => 'glpi_plugin_sservices_categories',
            'field' => 'name',
            'name' => __('Category', SSERVICES_SSERVICES),
            'linkfield' => 'plugin_sservices_categories_id',
            'datatype' => 'dropdown',
            'massiveaction' => true,
        ];

        $tab[] = [
            'id' => 600,
            'table' => 'glpi_users',
            'field' => 'name',
            'name' => __('Technician in charge', SSERVICES_SSERVICES),
            'linkfield' => 'users_id',
            'datatype' => 'dropdown',
            'massiveaction' => true,
            'right' => 'interface'
        ];

        $tab[] = [
            'id' => 700,
            'table' => 'glpi_groups',
            'field' => 'name',
            'name' => __('Group in charge', SSERVICES_SSERVICES),
            'linkfield' => 'groups_id',
            'datatype' => 'dropdown',
            'massiveaction' => true,
        ];

        $tab[] = [
            'id' => 800,
            'table' => 'glpi_plugin_sservices_localusers',
            'field' => 'name',
            'name' => __('Local User', SSERVICES_SSERVICES),
            'linkfield' => 'plugin_sservices_localusers_id',
            'datatype' => 'dropdown',
            'massiveaction' => true,
        ];

        $tab[] = [
            'id' => 900,
            'table' => 'glpi_plugin_sservices_visibilities',
            'field' => 'name',
            'name' => __('Visibility', SSERVICES_SSERVICES),
            'linkfield' => 'plugin_sservices_visibilities_id',
            'datatype' => 'dropdown',
            'massiveaction' => true,
        ];

        $tab[] = [
            'id' => 1000,
            'table' => $this->getTable(),
            'field' => 'is_monitored',
            'name' => __('Monitored', SSERVICES_SSERVICES),
            'datatype' => 'bool',
            'massiveaction' => true,
        ];

        $tab[] = [
            'id' => 1100,
            'table' => 'glpi_plugin_sservices_installationmethods',
            'field' => 'name',
            'name' => __('Installation Method', SSERVICES_SSERVICES),
            'linkfield' => 'plugin_sservices_installationmethods_id',
            'datatype' => 'dropdown',
            'massiveaction' => true,
        ];

        $tab[] = [
            'id' => 1200,
            'table' => $this->getTable(),
            'field' => 'comment',
            'name' => __('Comment', SSERVICES_SSERVICES),
            'datatype' => 'string',
            'massiveaction' => true,
        ];

        return $tab;
    }

    public function getSpecificMassiveActions($checkitem = null): array
    {
        $actions = parent::getSpecificMassiveActions($checkitem);

        $actions[__CLASS__ . MassiveAction::CLASS_ACTION_SEPARATOR . 'copy_services_to_computer'] =
            __('Copy service(s)', SSERVICES_SSERVICES);

        return $actions;
    }

    public static function showMassiveActionsSubForm(MassiveAction $ma): bool
    {
        switch ($ma->getAction()) {
            case 'copy_services_to_computer':
                echo __('Computer', SSERVICES_SSERVICES) . "&nbsp;&nbsp;";
                \Computer::dropdown(['name' => 'computers_id', 'used' => []]);
                echo '<br><br>';
                echo Html::submit(_x('button', 'Submit'), ['name' => 'massiveaction']);
                return true;
        }

        return parent::showMassiveActionsSubForm($ma);
    }

    public static function processMassiveActionsForOneItemtype(
        MassiveAction $ma,
        CommonDBTM $item,
        array $ids
    ) {
        switch ($ma->getAction()) {
            case 'copy_services_to_computer' :
                if ($item->getType() == SService::class && $item instanceof SService) {
                    $input = $ma->getInput();

                    foreach ($ids as $id) {
                        if (
                            $item->getFromDB($id) && $item->copyToComputer($input)
                        ) {
                            $ma->itemDone($item->getType(), $id, MassiveAction::ACTION_OK);
                        } else {
                            // Example of ko count
                            $ma->itemDone($item->getType(), $id, MassiveAction::ACTION_KO);
                        }
                    }
                } else {
                    // When nothing is possible ...
                    $message = __('Refusing to copy item type ' . $item->getType(), SSERVICES_SSERVICES);
                    $ma->addMessage($message);
                    Session::addMessageAfterRedirect($message, WARNING);
                }

                return;
        }

        parent::processMassiveActionsForOneItemtype($ma, $item, $ids);
    }

    public function copyToComputer(array $input): bool
    {
        $newComputerId = $input['computers_id'] ?? null;

        if (empty($newComputerId) || $newComputerId == $this->fields['computers_id']) {
            return false;
        }

        $newInput = $this->fields;
        unset($newInput['id']);
        $newInput['computers_id'] = $newComputerId;

        $this->add($newInput);

        return true;
    }

    public function getTabNameForItem(CommonGLPI $item, $withtemplate = 0): string
    {
        $tabName = __('Services', SSERVICES_SSERVICES);
        $nb = 0;

        if ($_SESSION['glpishow_count_on_tabs']) {
            $nb = self::countForItem($item);
        }

        switch ($item::getType()) {
            case Computer::class:
                return self::createTabEntry($tabName, $nb);
        }

        return '';
    }

    /**
     * @param $item    CommonDBTM object
     *
     * @return number
     **/
    public static function countForItem(CommonGLPI $item)
    {
        return countElementsInTable(
            'glpi_plugin_sservices_sservices',
            [
                'computers_id' => $item->getID(),
                'is_deleted' => 0,
            ]
        );
    }

    public static function displayTabContentForItem(CommonGLPI $item, $tabnum = 1, $withtemplate = 0): bool
    {
        switch ($item::getType()) {
            case Computer::class:
                //display form for computers
                self::displayTabContentForComputer($item);
                break;
        }

        return true;
    }

    private static function displayTabContentForComputer(CommonGLPI $item)
    {
//var_dump($item::getType(), \Session::getActiveTab($item::getType()), $item::getFormURLWithID($item->getID()));
//var_dump($_REQUEST);

        echo "<h3>" . SService::getMenuName() . "</h3>";

        $computersId = $item->getID();

        echo "<div class='center firstbloc'>";
        echo "<a class='btn btn-primary' href='" . self::getFormURL() . "?computers_id=$computersId" . "'>";
        echo __('Add Service');
        echo "</a></div>\n";

        $params = [
            'criteria' => [
                [
                    'field' => 300,        // field index in search options
                    'searchtype' => 'equals',  // type of search
                    'value' => $item->getID(),         // value to search
                ],
            ],
            //'target' => $item::getFormURL() . '?id=' . $computersId,
	    'target' => $item::getFormURLWithID($computersId),
            'mainform' => false,
            'is_deleted' => 0,
            'showmassiveactions' => 1,
            'export_all' => 1,
//            'show_footer' => false,
            'no_sort' => 1,
        ];

//        echo '<form metod="POST">';
//        echo "<input type='hidden' name='id' value='{$item->getID()}'>";
//        Search::showGenericSearch(SService::class, $params);
//        echo '<input type="submit" value="submit">';

//        echo '<input type="hidden" name="forcetab" value="GlpiPlugin\SServices\SService$1">';
//        echo '</form>';

//var_dump($_SESSION['glpisearch'][SService::class]);

        $preparedParams = Search::prepareDatasForSearch(SService::class, $params);
        $managedParams = Search::manageParams(SService::class, $params);

//die(var_dump($managedParams['target']));

        Search::showList(SService::class, $preparedParams['search']);
//        Search::showList(SService::class, $managedParams);

        $js = <<<JAVASCRIPT
         $(function() {
            $('input[name="is_deleted"]').parent('label').hide();
            $('input.fold-search').parent('label').hide();
            $('div.search-footer').hide();
         });
JAVASCRIPT;

        echo Html::scriptBlock($js);
    }

//    public static function getSpecificValueToDisplay($field, $values, array $options = [])
//    {
//        return '';
//    }
}
